apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-deploy
  labels:
    app: analyzer
spec:
  replicas: 2
  selector:
    matchLabels:
        app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
        - name: analyzer
          image: hongdabagi/smishing-analyzer
          ports:
            - containerPort: 8000
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                    name: sookmissing-secret
                    key: GOOGLE_API_KEY
                    
            