apiVersion: v1
kind: Service
metadata:
  name: analyzer-service
  labels:
    app: analyzer
spec:
  type: ClusterIP
  selector:
    app: analyzer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000