apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-server
spec: 
  type: ClusterIP  
  selector:       
    app: api-server 
  ports:         
    - protocol: TCP
      port: 8000
      targetPort: 8000